library:
  source-dirs: src
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- bytestring
- text
- discord-haskell
- serialport
- base >= 4.7 && < 5
name: rice-bot
version: 0.1.0.0
extra-source-files:
- README.md
author: Author name here
github: githubuser/rice-bot
license: BSD3
executables:
  rice-bot-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rice-bot
description: Please see the README on GitHub at <https://github.com/githubuser/rice-bot#readme>
